apiVersion: apps/v1
kind: Deployment
metadata:
  name: arussel-feedback-api
  namespace: arussel-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arussel-feedback-api
  template:
    metadata:
      labels:
        app: arussel-feedback-api
    spec:
      containers:
      - name: arussel-feedback-api
        image: ${CICD_IMAGE}:v1.0.${CICD_EXECUTION_SEQUENCE}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: Aruss_Feedback_Psql_Connection
          valueFrom:
            secretKeyRef:
              name: arussel-feedback-psql-config
              key: connectionString
        - name: Aruss_Feedback_AuthUrl
          valueFrom:
            secretKeyRef:
              name: arussel-feedback-client-config
              key: authority
        - name: Aruss_Feedback_Write_Scope
          valueFrom:
            secretKeyRef:
              name: arussel-feedback-client-config
              key: arussel-feedback-write-scope
        - name: Aruss_Feedback_Read_Scope
          valueFrom:
            secretKeyRef:
              name: arussel-feedback-client-config
              key: arussel-feedback-read-scope
        - name: Aruss_Feedback_Scope
          valueFrom:
            secretKeyRef:
              name: arussel-feedback-client-config
              key: arussel-feedback-scope   
        - name: Aruss_Feedback_ScopeSecret
          valueFrom:
            secretKeyRef:
              name: arussel-feedback-client-config
              key: arussel-feedback-secret
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
          failureThreshold: 3
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /health/live
            port: 80
          failureThreshold: 60
          periodSeconds: 10  
      imagePullSecrets:
      - name: aruss-pipeline-registry
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: arussel-feedback-api
  namespace: arussel-poc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: arussel-feedback-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60
---
apiVersion: v1
kind: Service
metadata:
  namespace: arussel-poc
  name: arussel-feedback-api
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: arussel-feedback-api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: arussel-feedback-api
  namespace: arussel-poc
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: aruss-feedback-api.atriarch.systems
    http:
      paths:
      - path: /
        backend:
          serviceName: arussel-feedback-api
          servicePort: http
